export const DEPARTMENTS = [
  'Computer Science',
  'Software Engineering',
  'Information Technology',
  'Cybersecurity',
  'Data Science',
  'Mathematics',
  'Statistics',
  'Physics',
  'Chemistry',
  'Biology',
  'Engineering (Electrical)',
  'Engineering (Mechanical)',
  'Engineering (Civil)',
  'Engineering (Chemical)',
  'Business Administration',
  'Accounting',
  'Economics',
  'Mass Communication',
  'Political Science',
  'Law',
  'Medicine',
  'Nursing',
  'Pharmacy',
  'Education',
  'English Language',
  'History',
  'Philosophy',
  'Psychology',
  'Sociology',
  'Agriculture',
  'Architecture',
  'Estate Management',
  'Geography',
  'Geology',
  'Marine Science',
  'Environmental Science',
  'Fine Arts',
  'Performing Arts',
  'Library Science',
  'Public Administration',
  'International Relations',
  'Criminology',
  'Forensic Science',
  'Food Science & Technology',
  'Human Kinetics',
  'Social Work',
]

export const LEVELS = [
  '100 Level',
  '200 Level',
  '300 Level',
  '400 Level',
  '500 Level',
  '600 Level',
  '700 Level',
  'Postgraduate',
]
