const NIGERIAN_UNIVERSITIES = [
  'Abubakar Tafawa Balewa University (ATBU)',
  'Adekunle Ajasin University (AAU)',
  'Akwa Ibom State University (AKSU)',
  'Alex Ekwueme Federal University (AE-FUNAI)',
  'Ambrose Alli University (AAU)',
  'Bayero University Kano (BUK)',
  'Benson Idahosa University (BIU)',
  'Bowen University',
  'Caleb University',
  'Chukwuemeka Odumegwu Ojukwu University (COOU)',
  'Covenant University',
  'Cross River University of Technology (CRUTECH)',
  'Delta State University (DELSU)',
  'Ebonyi State University (EBSU)',
  'Edo State University (EDSU)',
  'Ekiti State University (EKSU)',
  'Elizade University',
  'Enugu State University of Science and Technology (ESUT)',
  'Federal University of Agriculture Abeokuta (FUNAAB)',
  'Federal University of Petroleum Resources Effurun (FUPRE)',
  'Federal University of Technology Akure (FUTA)',
  'Federal University of Technology Minna (FUTMINNA)',
  'Federal University of Technology Owerri (FUTO)',
  'Federal University Dutse (FUD)',
  'Federal University Dutsin-Ma (FUDMA)',
  'Federal University Gashua (FUGASHUA)',
  'Federal University Gusau (FUGUS)',
  'Federal University Kashere (FUK)',
  'Federal University Lafia (FULAFIA)',
  'Federal University Lokoja (FULOKOJA)',
  'Federal University Ndifu-Alike (FUNAI)',
  'Federal University Otuoke (FUO)',
  'Federal University Oye-Ekiti (FUOYE)',
  'Federal University Wukari (FUW)',
  'Federal College of Education (Technical) Akoka',
  'Gombe State University (GSU)',
  'Igbinedion University Okada',
  'Ignatius Ajuru University of Education (IAUE)',
  'Imo State University (IMSU)',
  'Joseph Ayo Babalola University (JABU)',
  'Kaduna State University (KASU)',
  'Kano University of Science and Technology (KUST)',
  'Kwara State University (KWASU)',
  'Lagos State University (LASU)',
  'Landmark University',
  'Lead City University',
  'Madonna University',
  'Michael Okpara University of Agriculture (MOUAU)',
  'Modibbo Adama University (MAU)',
  'Nasarawa State University (NSUK)',
  'National Open University of Nigeria (NOUN)',
  'Niger Delta University (NDU)',
  'Nigerian Defence Academy (NDA)',
  'Nigerian Turkish Nile University',
  'Obafemi Awolowo University (OAU)',
  'Olabisi Onabanjo University (OOU)',
  'Ondo State University of Science and Technology (OSUSTECH)',
  'Osun State University (UNIOSUN)',
  'Pan-Atlantic University',
  'Plateau State University (PLASU)',
  'Redeemer\'s University',
  'Rivers State University (RSU)',
  'Tai Solarin University of Education (TASUED)',
  'Taraba State University (TSU)',
  'Umaru Musa Yar\'Adua University (UMYU)',
  'University of Abuja (UNIABUJA)',
  'University of Agriculture Makurdi (UAM)',
  'University of Benin (UNIBEN)',
  'University of Calabar (UNICAL)',
  'University of Ibadan (UI)',
  'University of Ilorin (UNILORIN)',
  'University of Jos (UNIJOS)',
  'University of Lagos (UNILAG)',
  'University of Maiduguri (UNIMAID)',
  'University of Nigeria Nsukka (UNN)',
  'University of Port Harcourt (UNIPORT)',
  'University of Uyo (UNIUYO)',
  'Usmanu Danfodiyo University (UDUSOK)',
  'Veritas University',
  'Wellspring University',
  'Wesley University',
  'Western Delta University',
  'Yaba College of Technology (YABATECH)',
  'Yobe State University (YSU)',
]

export default NIGERIAN_UNIVERSITIES
